version: '3.4'
services:
  app:
    build:
        context: .
        dockerfile: Dockerfile
        target: build
    environment:
      DB_HOST: db
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: payments_svc
      POSTGRES_PASSWORD: payments
      POSTGRES_DB: payments
    command:
      - -p 5433
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d