version: '3.4'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: database
      DB_PORT: 5432
    depends_on:
      - database
    ports:
      - "8080:8080"
  database:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: payments_svc
      POSTGRES_PASSWORD: payments
      POSTGRES_DB: payments
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
