spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5433/payments
    username: payments_svc
    password: payments
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    generate-ddl: false


wallet:
  endpoint: http://${WALLET_HOST:mockoon.tools.getontop.com}:3000/wallets

payments:
  endpoint: http://${PAYMENTS_HOST:mockoon.tools.getontop.com}:3000/api/v1/payments
